name: 🧩 Widget Request
description: Request support for a new widget.
title: "feat(widget): WIDGET_NAME"
labels: ["feature", "widget", "triage"]
projects: ["dashbarr/1"]
type: feature
assignees:
  - "inman-sebastian"
body:
  - type: textarea
    attributes:
      label: "Additional Information"
      description: "Any other information about the integration you want added to Dashbarr."
